config/routes.rb
Rails.application.routes.draw do
root "pages#index"

  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.fetch(:page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConoceTusVecinos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<header>
  <div class="small-container">
    <%= image_tag("conoce-a-tus-vecinos.png", class: "logo") %>
    <ul>
      <%= link_to "Saber más" %>
    </ul>
  </div>
</header>

<div class="small-container">
  <div class="col col-50 noticias">
    <%= image_tag ("noticias.jpeg"), class: "android-iphone" %>
  </div>
  <div class="col col-50 description">
    <h4 class="titleloc">Descarga gratis la app <br> y acércate a los vecinos de tu comunidad</h4>
    <center>
      <a class="btn blue big">App store</a>
      <a class="btn blue big">Google play</a>
    </center>
  </div>
</div>

<div class="full-container fondo-blanco second">
  <div class="small-container">
    <div class="col col-50">
      <h4 class="identifica">Identifica la comunidad de tus vecinos a través de tu código postal y después ingresa tu colonia</h4>
    </div>
    <div class="col col-50">
      <%= image_tag("Map.png", class: "Mapa") %>
    </div>
  </div>
</div>
<div class="full-container localizacion ">
  <div class="small-container titleloc">

      <h1>Localizanos en nuestras oficinas</h1>


    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d941.655911066017!2d-103.6899736878075!3d19.25522731996561!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x84255a8ec6a7ee45%3A0xd06c856c6d209076!2sSalas+de+Convenciones!5e0!3m2!1ses-419!2smx!4v1543159443215" width="100%" height="250" frameborder="0" style="border:0" allowfullscreen></iframe>

  </div>

</div>
<footer>
  <center>
    <div class="full-container fondo-blanco">
      <div class="small-container">
        <h4>Contáctanos</h4>

        <span><%= image_tag ("facebook.png"), class: "facebook" %></span>
        <span><%= image_tag ("twitter.png"), class: "twitter" %></span>
        <span><%= image_tag ("github-logo.png"), class: "github-logo" %></span>
        <span><%= image_tag ("instagram.png"), class: "instagram" %></span>

      </div>
    </div>
  </center>
</footer>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>